security:
  oauth2.resource.jwk.key-set-uri: ${JWT_KEY_SET_URI:https://www.googleapis.com/oauth2/v3/certs}
  cors:
    allowedOrigins: "*"
    allowedMethods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"


# Kafka configuration
spring:
  cloud:
    stream:
      kafka.binder:
        zkNodes: ${ZOOKEEPER_ENDPOINT:localhost:2181}
        brokers: ${KAFKABROKER_ENDPOINT:localhost:9092}
    bindings:
      publishing-state-changed.content-type: application/avro;type=StateChangedEvent
